config/routes.rb
BitcoinBank::Application.routes.draw do
  resources :invoices, :only => [:index, :new, :create, :show, :destroy]

  resource :user, :only => [:edit, :update] do
    get :ga_otp_configuration
    post :reset_ga_otp_secret
    put :update_password
    get :edit_password

    resources :yubikeys, :only => [:index, :create, :destroy]
    resources :bank_accounts, :only => [:index, :create, :destroy]
    resources :tickets do
      resources :comments, :only => :create
      member do
        post :close
        post :reopen
        post :solve
      end
    end
  end

  devise_for :users, :controllers => { :registrations => "registrations" }

  # These routes need some loving :/
  resource :chart, :path => "charts", :only => [] do
    get :price
  end

  resource :account, :only => [:show] do
    match '/balance/:currency',
      :action => 'balance',
      :as => 'balance',
      :only => :get
      
    get :deposit
    get :pecunix_deposit_form
    
    resources :transfers, :only => [:index, :new, :create, :show] 
    
    resources :trades, 
      :only => [:index]
    
    resources :invoices

    resources :trade_orders, :only => [:index, :new, :create, :destroy] do
      post :activate
    end
  end

  match "/s/:name" => "static_pages#show", :as => :static
  
  match '/third_party_callbacks/:action',
    :controller => :third_party_callbacks

  namespace :admin do
    %w{ announcements yubikeys static_pages currencies tickets comments }.each { |r| resources(r.to_sym) {as_routes} }

    resources :pending_transfers do
      as_routes
      
      member do
        post :process_tx
      end
    end
    
    resources :users do
      as_routes
      
      member do
        get :balances
      end
      
      resources :account_operations do
        as_routes
      end
    end
    
    match '/balances', :to => 'informations#balances', :as => :balances
  end
  
  match '/qrcode/:data.png' => 'qrcodes#show', :as => :qrcode
  
  match '/order_book' => 'trade_orders#book'

  match '/trades' => 'trades#all_trades'

  match '/ticker' => 'trades#ticker'

  match '/economy' => 'informations#economy', :as => :economy

  match '/support' => 'informations#support', :as => :support

  root :to => 'informations#welcome'
end

app/models/user.rb
class User < Account
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable,
    :ga_otp_authenticatable,
    :yk_otp_authenticatable,
    :registerable,
    :confirmable,
    :recoverable,
    :trackable,
    :validatable,
    :lockable,
    :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :password, :password_confirmation, :remember_me, :time_zone, 
    :merchant, :require_ga_otp, :require_yk_otp, :full_name, :address

  attr_accessor :captcha,
    :skip_captcha,
    :new_password,
    :new_password_confirmation,
    :current_password

  before_validation :generate_name,
    :on => :create

  has_many :trade_orders,
    :dependent => :destroy

  has_many :purchase_trades,
    :class_name => "Trade",
    :foreign_key => "buyer_id"

  has_many :sale_trades,
    :class_name => "Trade",
    :foreign_key => "seller_id"

  has_many :invoices,
    :dependent => :destroy

  has_many :yubikeys,
    :dependent => :destroy

  has_many :bank_accounts,
    :dependent => :destroy

  has_many :tickets,
    :dependent => :destroy

  validates :email,
    :uniqueness => true,
    :presence => true

  validate :captcha do
    if captcha.nil? and new_record?
      unless skip_captcha
        errors[:captcha] << I18n.t("errors.answer_incorrect")
      end
    end
  end

  def captcha_checked!
    self.captcha = true
  end

  def bitcoin_address
    super or (generate_new_address && super)
  end

  def qr_code
    if @qrcode.nil?
      @qrcode = RQRCode::QRCode.new(bitcoin_address, :size => 6)
    end
    @qrcode
  end

  def confirm!
    super
    UserMailer.registration_confirmation(self).deliver
  end

  protected

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    name = conditions.delete(:name)
    where(conditions).where(["name = :value OR email = :value", { :value => name }]).first
  end

  def generate_name
    self.name = "BC-U#{"%06d" % (rand * 10 ** 6).to_i}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  def conditions_for_collection
    unless params[:currency].blank?
      raise "Currency not recognized" unless params[:currency] =~/^[A-Za-z]+$/
      @conditions = "((SELECT SUM(amount) FROM account_operations WHERE account_operations.account_id = accounts.id AND account_operations.currency = '#{params[:currency]}') > 0)"
    end
  end


  def balances
    @balances = {}
    @user = User.find(params[:id])

    Currency.all.map(&:code).each do |c|
      @balances[c] = @user.balance(c)
    end
  end

  active_scaffold :user do |config|
    config.actions.exclude :create, :delete

    config.columns = [
      :id,
      :name,
      :full_name,
      :email,
      :address,
      :require_ga_otp,
      :require_yk_otp,
      :merchant,
      :time_zone,
      :bitcoin_address,
      :confirmation_sent_at,
      :confirmed_at,
      :current_sign_in_at,
      :current_sign_in_ip,
      :failed_attempts,
      :last_sign_in_at,
      :last_sign_in_ip,
      :locked_at,
      :commission_rate
    ]

    config.update.columns = [
      :commission_rate
    ]

    config.list.columns = [
      :id,
      :name,
      :email
    ]

    config.show.columns = [
      :id,
      :name,
      :full_name,
      :email,
      :address,
      :require_ga_otp,
      :require_yk_otp,
      :merchant,
      :time_zone,
      :bitcoin_address,
      :confirmation_sent_at,
      :confirmed_at,
      :current_sign_in_at,
      :current_sign_in_ip,
      :failed_attempts,
      :last_sign_in_at,
      :last_sign_in_ip,
      :locked_at,
      :commission_rate
    ]

    config.columns[:merchant].inplace_edit = true
    config.columns[:require_ga_otp].inplace_edit = true
    config.columns[:require_yk_otp].inplace_edit = true

    config.search.columns << :id

    config.nested.add_link(:yubikeys)

    config.action_links.add :balances,
      :type => :member,
      :label => "Balances",
      :action => "balances",
      :controller => "admin/users",
      :page => true
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  skip_before_filter :authenticate_user!,
    :only => [:new, :create]

  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end

  def create
    @user = User.new(params[:user])

    verify_recaptcha and @user.captcha_checked!

    if @user.save
      session[:current_user_id] = @user.id
      redirect_to account_path, :notice => (t :account_created)
    else
      render :action => :new
    end
  end

  def update
    @user = current_user

    params[:user].delete(:full_name) unless @user.full_name.blank?
    params[:user].delete(:address) unless @user.address.blank?
    
    if @user.update_attributes(params[:user])
      redirect_to edit_user_path,
        :notice => (t :account_updated)
    else
      render :action => :edit
    end
  end

  def reset_ga_otp_secret
    current_user.generate_ga_otp_secret && current_user.save!

    redirect_to ga_otp_configuration_user_path,
      :notice => t("users.ga_otp_configuration.reset")
  end
  
  def update_password
    @user = current_user

    if @user.update_with_password(params[:user])
      sign_in(@user, :bypass => true)
      
      redirect_to edit_user_path, :notice => t("users.password_change_form.password_updated")
    else
      render :edit_password
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def id_column(record)
    record.id.to_s
  end
  
  def name_column(record)
    link_to record.name, admin_user_account_operations_path(record)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user, :as => :user, :url => user_path do |f|
  = errors_for @user, :message => "error_updating_account"

  - unless @user.new_record?
    .form-field
      = f.label :name
      = f.text_field :name, :disabled => true

  .form-field
    = f.label :email
    = f.text_field :email, :disabled => true

  .form-field
    = f.label :full_name
    = f.text_field :full_name, :disabled => !@user.full_name.blank?

  .form-field
    = f.label :address
    = f.text_area :address, :disabled => !@user.address.blank?, :rows => 4

  .form-field
    = f.label :time_zone
    = f.time_zone_select :time_zone, nil, :prompt => "--"
    .explanation= t(".time_zone_explanation")

  %div{ :style => "clear:both;" }

  - unless @user.new_record?
    %fieldset
      %legend= t(".additional_authentication_requirements")
      .form-field
        = f.label :require_ga_otp
        = f.check_box :require_ga_otp, :class => "checkbox"
        .explanation= link_to t(".ga_otp_config"), ga_otp_configuration_user_path

      .form-field
        = f.label :require_yk_otp
        = f.check_box :require_yk_otp, :class => "checkbox"
        .explanation= link_to t(".yk_otp_config"), user_yubikeys_path

    %fieldset
      %legend= t("activerecord.models.bank_account.other")
      %p= t(".registered_bank_accounts", :count => current_user.bank_accounts.count)
      %p= link_to t(".manage_bank_accounts"), user_bank_accounts_path

    %fieldset
      %legend= t(".notifications")
      .form-field
        = f.label :notify_on_trade
        = f.check_box :notify_on_trade, :class => "checkbox"
        .explanation= t(".notify_on_trade_explanation")        

    %fieldset
      %legend= t(".api_tools")
      .form-field
        = f.label :merchant
        = f.check_box :merchant, :class => "checkbox"
        .explanation= t(".merchant_explanation")


  - if @user.new_record?
    .recaptcha-field
      %label{ :for => "recaptcha_response_field" } t(".turing_test")
      = f.text_field :account, :disabled => true
      .recaptcha-input= recaptcha_tags :ssl => true

  .form-field
    = f.submit t(".submit"), :class => 'submit'

app/views/users/_password_change_form.html.haml
%fieldset
  %legend= t(".change_password")
  .form-field
    = f.label :current_password
    = f.password_field :current_password

  .form-field
    = f.label :password
    = f.password_field :password, :value => ""

  .form-field
    = f.label :password_confirmation
    = f.password_field :password_confirmation

.form-field
  = f.submit t(".submit"), :class => 'submit'

app/views/users/edit.html.haml
%h1= t :account_details_title

= render 'form'

%br

= form_for @user, :as => :user, :url => update_password_user_path do |f|
  = render :partial => 'password_change_form', :locals => { :f => f }

app/views/users/edit_password.html.haml
= form_for @user, :as => :user, :url => update_password_user_path do |f|
  = errors_for @user, :message => "error_updating_password"
  = render :partial => 'password_change_form', :locals => { :f => f }

app/views/users/ga_otp_configuration.en.html.haml
%h1 Required steps for TOTP authentication
%h2 Why use one-time-password authentication ?
%p
  TOTP authentication adds a security layer on top of the login/password authentication
  mechanism. For your account to be compromised, an attacker must not only know your
  password, but also know your shared-secret or compromise your mobile device.e.
%p
  If you activate the "Require TOTP" option in your account settings you won't be
  able to sign in without providing a TOTP token. You can use the same token multiple
  times, but the token is time based and is only valid for 30 seconds. You need a
  Blackebbery, Android or iPhone for the token generation.

%h2 Reset your shared-secret
%p
  If you think your mobile device has been compromised or if you think someone
  got a hold of your shared-secret you <strong>must</strong> reset it.
%p
  You will need to update your mobile device configuration.
%br
%p
  = form_tag reset_ga_otp_secret_user_path, :method => :post do
    = submit_tag "Reset shared-secret", :class => "submit"

%h2 Configuration
%p
  %ul
    %li Install the #{link_to "Google Authenticator", "http://www.google.com/support/accounts/bin/answer.py?hl=en&answer=1066447", :target => "_blank"} app on your mobile device
    %li
      Configure the shared secret, either:
      %ul
        %li manually, or
        %li automatically by scanning the QR code below.

%h3 Automatic configuration

%p Scan the QR code to automatically configure your mobile device.

= qrcode_image_tag current_user.ga_provisioning_uri

%h3 Manual configuration

%p Use these parameters to configure your device
%br
%table.default.details
  %tr
    %th Account
    %td= current_user.name
  %tr
    %th Token type
    %td Time-based
  %tr
    %th Shared secret
    %td.fixed= current_user.ga_otp_secret

app/views/users/ga_otp_configuration.fr.html.haml
%h1 Configuration de l'authentification avec jeton TOTP
%h2 Objectif
%p
  L'authentification avec jeton TOTP a pour but de rajouter une couche de sécurité
  supplémentaire à l'authentification utilisant un idenfiant et un mot de passe.
%p
  Si vous activez l'option "Demander jeton TOTP" au niveau des paramètres de votre
  compte vous devrez générer un code de connexion différent à chaque connexion. Vous
  aurez besoin d'un téléphone Blackberry, Android ou iPhone pour la génération du
  code de connexion.

%h2 Ré-initialiser votre secret partagé
%p
  Si vous pensez que votre téléphone a été compromis, ou si vous pensez que quelqu'un
  a pris connaissance de votre secret partagé vous <strong>devez</strong> le ré-initialiser.
%p
  Vous devrez mettre à jour la configuration de votre téléphone.
%br
%p
  = form_tag reset_ga_otp_secret_user_path, :method => :post do
    = submit_tag "Ré-initialiser", :class => "submit"

%h2 Configuration
%p
  %ul
    %li Installez l'application #{link_to "Google Authenticator", "http://www.google.com/support/accounts/bin/answer.py?hl=en&answer=1066447", :target => "_blank"}
    %li
      Configurez le secret partagé qui permettra de générer des codes d'authentification, soit :
      %ul
        %li manuellement, soit
        %li automatiquement en scannant le code QR ci-dessous.

%h3 Configuration automatique

%p Scannez le code QR afin de configurer automatiquement votre générateur de codes d'authentification.

= qrcode_image_tag current_user.ga_provisioning_uri

%h3 Configuration manuelle

%p Utilisez les paramètres suivants pour configurer votre générateur de codes d'authentification
%br
%table.default.details
  %tr
    %th Compte
    %td= current_user.name
  %tr
    %th Type de code
    %td Temporel
  %tr
    %th Secret partagé
    %td.fixed= current_user.ga_otp_secret

app/views/users/new.html.haml
%h1= t :sign_up_for_account_title

= render 'form'